site_name: git-commit-ectomy
docs_dir: docs
site_dir: site
theme:
  name: null
  custom_dir: 'mkdocs-material/material'
  palette:
    primary: 'deep orange'
    accent: 'deep orange'
  logo:
    icon: 'dns'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

extra_css:
  - css/custom.css
pages:
  - 'Index' : 'index.md'
