site_name: git-commit-ectomy
docs_dir: docs
site_dir: site
copyright: Copyright &copy; 2018 Charles Reid
site_url: https://pages.charlesreid1.com/git-commit-ectomy/
repo_name: charlesreid1/git-commit-ectomy
repo_url: https://git.charlesreid1.com/charlesreid1/git-commit-ectomy
edit_uri: ""
theme:
  name: null
  custom_dir: 'mkdocs-material/material'
  palette:
    primary: 'orange'
    accent: 'orange'
  logo:
    icon: 'announcement'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

extra_css:
  - css/custom.css
pages:
  - 'Index' : 'index.md'
